# my global config
global:
  scrape_interval:     60s
  evaluation_interval: 60s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: minio
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ['minio:9000']
  - job_name: teamcity-backup
    metrics_path: /metrics
    static_configs:
      - targets: ['teamcity-backup:8765']
